repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-added-large-files
        name: check-added-large-files

      - id: check-case-conflict
        name: check-case-conflict

      - id: end-of-file-fixer
        name: end-of-file-fixer

      - id: requirements-txt-fixer
        name: requirements-txt-sorter

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        name: CODE_FORMATTER
        language: python

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: IMPORT_FORMATTER

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        name: LINTER
        language: python
