wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: huggingface
    huggingface_version: 4.19.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1655414839
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 31
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 31
      - 49
      - 51
      - 53
      - 55
      4: 3.8.13
      5: 0.12.17
      6: 4.19.2
      8:
      - 5
features:
  desc: null
  value: null
grid:
  desc: null
  value: false
max_depth:
  desc: null
  value: 10
min_samples:
  desc: null
  value: 2
n_estimators:
  desc: null
  value: 100
result_path:
  desc: null
  value: ./transformer_predictions.txt
subparser_ml_clf_rf:
  desc: null
  value: true
train_file:
  desc: null
  value: ../data/
verbose:
  desc: null
  value: false
